version: '3.8'

services:
  web:
    build: .
    command: gunicorn file_share_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./file_share_project:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: file_share_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
